name: 'Test'
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    - name: 'Install Node'
      uses: actions/setup-node@v4
    - name: 'Install Deps'
      run: npm install
    - name: 'Test'
      run: npm run test
